#!/usr/bin/env bash

# mvn command wrapper script - with commonly used options and flags

# Since using JDK7 - prevent error downloading from Maven Central: Received fatal alert: protocol_version
# See: https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/
mvn -Dhttps.protocols=TLSv1.2 -B -V $@